"""Add nullable salary currency and period fields

Revision ID: 346944245a53
Revises: 
Create Date: 2026-08-25 19:01:49.049654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '346944245a53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary_currency', sa.String(length=3), nullable=True))
    op.add_column('jobs', sa.Column('salary_period', sa.String(length=10), nullable=True))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('jobs', 'source_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_column('jobs', 'scraped_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.alter_column('jobs', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'source_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'salary_period')
    op.drop_column('jobs', 'salary_currency')
    # ### end Alembic commands ###
